### ISSUE TITLE
Report gives error when run inside docker container, but not on my normal host

### ISSUE THREAD

**Issue by ghost** [ctrf-io/newman-reporter-ctrf-json#19]
Below is the error from my docker logs.
Everything works great on my local machine, regardless of Node version.
Other Newman reporters work fine running inside Docker.

I tried this with official `newman` Docker image
```
docker pull postman/newman:6.1.3-ubuntu
```

Internally I believe this uses Node 16, and added this library with the Docker command
```
RUN npm install -g newman-reporter-ctrf-json
```

I also tried with Docker image
```
node:23.3.0-alpine
```

to make sure that the version of Node was not the problem.

The full `Dockerfile` for this is

```
FROM node:23.3.0-alpine AS test

RUN npm install -g newman
RUN npm install -g newman-reporter-html
RUN npm install -g newman-reporter-htmlextra
RUN npm install -g newman-reporter-ctrf-json

WORKDIR /output

ENTRYPOINT ["newman", "run"]
```
with arguments for tests and reporters specified in the the `compose.xml`

---

```
test-1  | /usr/local/lib/node_modules/newman-reporter-ctrf-json/dist/generate-report.js:86
test-1  |                             duration: execution.response.responseTime,
test-1  |                                                          ^
test-1  | 
test-1  | TypeError: Cannot read properties of undefined (reading 'responseTime')
test-1  |     at /usr/local/lib/node_modules/newman-reporter-ctrf-json/dist/generate-report.js:86:58
test-1  |     at Array.forEach (<anonymous>)
test-1  |     at /usr/local/lib/node_modules/newman-reporter-ctrf-json/dist/generate-report.js:79:42
test-1  |     at Array.forEach (<anonymous>)
test-1  |     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/newman-reporter-ctrf-json/dist/generate-report.js:76:36)
test-1  |     at EventEmitter.emit (node:events:525:35)
test-1  |     at /usr/local/lib/node_modules/newman/lib/run/index.js:345:33
test-1  |     at wrapper (/usr/local/lib/node_modules/newman/node_modules/async/internal/once.js:12:16)
test-1  |     at iteratorCallback (/usr/local/lib/node_modules/newman/node_modules/async/eachOf.js:56:13)
test-1  |     at /usr/local/lib/node_modules/newman/node_modules/async/internal/onlyOnce.js:12:16
test-1  |     at wrapper (/usr/local/lib/node_modules/newman/node_modules/async/dist/async.js:273:20)
test-1  |     at next (/usr/local/lib/node_modules/newman/node_modules/async/dist/async.js:5797:24)
test-1  |     at /usr/local/lib/node_modules/newman/node_modules/async/dist/async.js:329:20
test-1  |     at /usr/local/lib/node_modules/newman/lib/run/export-file.js:40:13
test-1  |     at FSReqCallback.oncomplete (node:fs:188:23)
```

**Comment by Dieff** [comment]
I had a really similar issue. For me, it was caused by TLS inspection on my corporate network. Node could not make a connection from inside a Docker container because my company's certificate wasn't installed in the container.

There is an issue in the reporter where it expects that the `response` property is always present, but this isn't true when the request failed. I fixed it in my PR.
