### ISSUE TITLE
Exception when running ctrf-json

### ISSUE THREAD

**Issue by douglasfsmn** [ctrf-io/newman-reporter-ctrf-json#9]
Hello,
Installed the ctrf-json reporter and executed with "-r ctrf-json" (using Newman version 6.1.3).  The following error was thrown. Am I missing something?  Thanks!

>newman run Automa.json -r ctrf-json
C:\Users\xxxxx\AppData\Roaming\npm\node_modules\newman-reporter-ctrf-json\dist\generate-report.js:69
                execution.assertions.forEach((assertion) => {
                                     ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at C:\Users\xxxxx\AppData\Roaming\npm\node_modules\newman-reporter-ctrf-json\dist\generate-report.js:69:38
    at Array.forEach (<anonymous>)
    at EventEmitter.<anonymous> (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\newman-reporter-ctrf-json\dist\generate-report.js:68:36)
    at EventEmitter.emit (node:events:531:35)
    at C:\Users\xxxxx\AppData\Roaming\npm\node_modules\newman\lib\run\index.js:345:33
    at wrapper (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\newman\node_modules\async\internal\once.js:12:16)
    at eachOfArrayLike (C:xxxxx\AppData\Roaming\npm\node_modules\newman\node_modules\async\eachOf.js:45:9)
    at eachOf (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\newman\node_modules\async\eachOf.js:181:12)
    at awaitable (C:xxxxx\AppData\Roaming\npm\node_modules\newman\node_modules\async\internal\awaitify.js:14:28)
    at eachLimit (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\newman\node_modules\async\each.js:125:33)
    at awaitable (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\newman\node_modules\async\internal\awaitify.js:14:28)
    at done (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\newman\lib\run\index.js:343:21)
    at C:xxxxx\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\backpack\index.js:58:34
    at PostmanCollectionRun._process (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\run.js:160:13)
    at PostmanCollectionRun.<anonymous> (C:xxxxx\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\run.js:166:76)
    at listOnTimeout (node:internal/timers:573:17)

**Comment by Ma11hewThomas** [comment]
Thanks for reporting! Please try v0.0.5

**Comment by douglasfsmn** [comment]
I am still getting the exception.  How should I be installing v0.0.5?  I suspect this is my problem.

**Comment by Ma11hewThomas** [comment]
In the same way you installed the package initially, can you try to install using version number, for example - 

```bash
npm install newman-reporter-ctrf-json@0.0.7
```

More instructions on custom reporters here https://learning.postman.com/docs/collections/using-newman-cli/newman-custom-reporters/#using-external-and-custom-reporters

**Comment by douglasfsmn** [comment]
I just installed using this, and get the same exception

npm install newman-reporter-ctrf-json@0.0.7
changed 1 package, and audited 2 packages in 2s
found 0 vulnerabilities

newman run Automa.json -r ctrf-json
/usr/local/lib/node_modules/newman-reporter-ctrf-json/dist/generate-report.js:69
                execution.assertions.forEach((assertion) => {
                                     ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at /usr/local/lib/node_modules/newman-reporter-ctrf-json/dist/generate-report.js:69:38
    at Array.forEach (<anonymous>)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/newman-reporter-ctrf-json/dist/generate-report.js:68:36)
    at EventEmitter.emit (node:events:529:35)
    at /usr/local/lib/node_modules/newman/lib/run/index.js:345:33
    at wrapper (/usr/local/lib/node_modules/newman/node_modules/async/internal/once.js:12:16)
    at eachOfArrayLike (/usr/local/lib/node_modules/newman/node_modules/async/eachOf.js:45:9)
    at eachOf (/usr/local/lib/node_modules/newman/node_modules/async/eachOf.js:181:12)
    at awaitable (/usr/local/lib/node_modules/newman/node_modules/async/internal/awaitify.js:14:28)
    at eachLimit (/usr/local/lib/node_modules/newman/node_modules/async/each.js:125:33)
    at awaitable (/usr/local/lib/node_modules/newman/node_modules/async/internal/awaitify.js:14:28)
    at done (/usr/local/lib/node_modules/newman/lib/run/index.js:343:21)
    at /usr/local/lib/node_modules/newman/node_modules/postman-runtime/lib/backpack/index.js:58:34
    at PostmanCollectionRun._process (/usr/local/lib/node_modules/newman/node_modules/postman-runtime/lib/runner/run.js:160:13)
    at PostmanCollectionRun.<anonymous> (/usr/local/lib/node_modules/newman/node_modules/postman-runtime/lib/runner/run.js:166:76)
    at listOnTimeout (node:internal/timers:569:17)

Node.js v18.20.1

**Comment by Ma11hewThomas** [comment]
Hello @douglasfsmn, I’m sorry to hear you’re facing this issue.

It looks like you’re still using version 0.0.4 or earlier, which contains the bug you reported. I can tell because your stack trace shows the error occurring at line 69 with Array.forEach(). This specific line is only present in version 0.0.4 or earlier [code](https://www.npmjs.com/package/newman-reporter-ctrf-json/v/0.0.4?activeTab=code), whereas in version 0.0.7 [code](https://www.npmjs.com/package/newman-reporter-ctrf-json/v/0.0.7?activeTab=code), the Array.forEach() is no longer at that line.

I suggest the following action: 

- Uninstall the old version globally or locally.
- Clear the npm cache to remove any residual files.
- Reinstall the latest version globally or locally.
- Verify the installation to ensure the correct version is installed.

**Step 1: Uninstall the Old Version**
To check if the reporter is installed globally, run:

```bash
npm list -g newman-reporter-ctrf-json
```

If it is listed, it means the reporter is installed globally.

**1.2. Check if Installed Locally**
To check if the reporter is installed locally within a project, navigate to the project directory and run:

```bash
npm list newman-reporter-ctrf-json
```

If it is listed, it means the reporter is installed locally.

**1.3. Uninstall Globally**
If the reporter is installed globally, you need to uninstall it globally:

```bash
npm uninstall -g newman-reporter-ctrf-json
```

**1.4. Uninstall Locally**
If the reporter is installed locally within a project, you need to uninstall it from the project directory:

```bash
npm uninstall newman-reporter-ctrf-json
```

**Step 2: Clear NPM Cache (Optional but Recommended)**
To ensure that no old versions are cached by npm, it’s a good idea to clear the npm cache:

```bash
npm cache clean --force
```

**Step 3: Reinstall the Latest Version of the Reporter
3.1. Install Globally**
If you want to install the reporter globally (available across all projects), run:

```bash
npm install -g newman-reporter-ctrf-json@latest
```

**3.2. Install Locally**
If you want to install the reporter locally within a specific project, navigate to the project directory and run:

```bash
npm install newman-reporter-ctrf-json@latest
```

**Step 4: Verify the Installation**
After installing, verify that the latest version is installed:

**4.1. Global Installation**

```bash
npm list -g newman-reporter-ctrf-json
```

**4.2. Local Installation**
Navigate to the project directory and run:

```bash
npm list newman-reporter-ctrf-json
```

**Comment by douglasfsmn** [comment]
Thank you - remove and reinstall did the trick.
